on:
  push:
    branches:
      - feature/ci

name: Build Packages

jobs:
  deb:
    name: Debian
    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sed 's/^deb /deb-src /' /etc/apt/sources.list >> /etc/apt/sources.list
        apt-get -y update
        apt-get -y install build-essential debhelper dpkg-sig fakeroot wget git
        apt-get -y build-dep libwacom

    - name: Build package
      run: |
        ./pkg/debian/makedeb

    - name: Prepare release
      run: |
        mkdir release
        mv ./pkg/debian/*.deb release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: debian-latest
        path: release
