on:
  push:
    tags:
      - v[0-9]+.*
      - testing-ci.*

name: Build Packages

jobs:
  build-deb:
    name: Debian
    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sed 's/^deb /deb-src /' /etc/apt/sources.list >> /etc/apt/sources.list
        apt-get -y update
        apt-get -y install build-essential debhelper dpkg-sig fakeroot wget git
        apt-get -y build-dep libwacom

    - name: Build package
      run: |
        ./pkg/debian/makedeb

    - name: Sign package
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/debian

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes
        export GPG_TTY=$(tty)

        # sign package
        dpkg-sig -g "--batch --no-tty" --sign builder -k $GPG_KEY_ID ./*.deb

    - name: Prepare release
      run: |
        mkdir release
        rm ./pkg/debian/libwacom-surface-dbgsym_*.deb
        mv ./pkg/debian/*.deb release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: debian-latest
        path: release

  build-f31:
    name: Build Fedora 31 package
    runs-on: ubuntu-latest
    container: fedora:31
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y rpmdevtools rpm-sign 'dnf-command(builddep)'
        dnf builddep -y pkg/fedora/libwacom-surface.spec

    - name: Build package
      run: |
        cd pkg/fedora

        # Build the .rpm packages
        ./makerpm

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/fedora/out

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes

        # sign package
        cd noarch
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

        cd ..

        cd x86_64
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

    - name: Prepare artifacts
      run: |
        cd pkg/fedora
        mkdir release

        cp out/noarch/* release/
        cp out/x86_64/* release/

        rm release/libwacom-surface-devel-*

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-31-latest
        path: pkg/fedora/release

  build-f30:
    name: Build Fedora 30 package
    runs-on: ubuntu-latest
    container: fedora:30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y rpmdevtools rpm-sign 'dnf-command(builddep)'
        dnf builddep -y pkg/fedora/libwacom-surface.spec

    - name: Build package
      run: |
        cd pkg/fedora

        # Build the .rpm packages
        ./makerpm

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/fedora/out

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes

        # sign package
        cd noarch
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

        cd ..

        cd x86_64
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

    - name: Prepare artifacts
      run: |
        cd pkg/fedora
        mkdir release

        cp out/noarch/* release/
        cp out/x86_64/* release/

        rm release/libwacom-surface-devel-*

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-30-latest
        path: pkg/fedora/release

  release:
    name: Publish release
    needs: [build-deb, build-f31, build-f30]
    runs-on: ubuntu-latest
    steps:
    - name: Download Debian artifacts
      uses: actions/download-artifact@v1
      with:
        name: debian-latest

    - name: Download Fedora 31 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-31-latest

    - name: Download Fedora 30 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-30-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-latest/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
